[theme]
# dark theme
primaryColor="#f63366"
backgroundColor="#0e1117"
secondaryBackgroundColor="#31333F"
textColor="#fafafa"
font="sans serif"

[server]
# headless = true
# you will need this for local development:
runOnSave = true
# you will need this if running docker on windows host:
# fileWatcherType = "poll"
